databaseChangeLog:
  - changeSet:
      id: product.001.create
      author: ghost.choe
      changes:
        - createTable:
            tableName: product
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
              - column:
                  name: name
                  type: varchar(255)
              - column:
                  name: description
                  type: varchar(4000)
              - column:
                  name: list_price
                  type: bigint
              - column:
                  name: created_at
                  type: timestamp with time zone
              - column:
                  name: updated_at
                  type: timestamp with time zone
